target(
  name='targets',
  dependencies=[
    ':stackage_package',
  ]
)

python_library(
  name='stackage_package',
  sources=['stackage_package.py'],
  dependencies=[
    'src/python/pants/base:target'
  ]
)
