# coding=utf-8
# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='tasks',
  sources=[
    'stack_bench.py',
    'stack_build.py',
    'stack_ghci.py',
    'stack_test.py',
  ],
  dependencies=[
    'src/python/pants/backend/core/tasks:common',
  ],
)
