# coding=utf-8
# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='tasks',
  sources=[
    'stack_install.py',
  ],
  dependencies=[
    'src/python/pants/backend/core/tasks:common',
  ],
)
